server:
    port: 8761

spring:
    application:
        name: service-discovery

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

    server:
        # ğŸ”’ Desactiva el modo de auto-preservaciÃ³n para limpiar instancias caÃ­das
        enable-self-preservation: false

        # ğŸ” Intervalo de limpieza de instancias desconectadas (1 minuto)
        eviction-interval-timer-in-ms: 60000

        # ğŸ’¡ Opcional: mejora estabilidad si hay muchos microservicios
        response-cache-update-interval-ms: 3000
        wait-time-in-ms-when-sync-empty: 0
